version: '2'
services:
  postgresql:
    image: docker.bintray.io/postgres:9.5.2
    container_name: postgresql
    ports:
     - 5432:5432
    environment:
     - POSTGRES_DB=artifactory
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:5.4.4
    container_name: artifactory
    ports:
     - 8081:8081
    depends_on:
     - postgresql
    links:
     - postgresql
    environment:
     - DB_TYPE=postgresql
     - DB_USER=admin
     - DB_PASSWORD=admin
     - EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000